### ISSUE TITLE
Improve the scheduler plugin for the actual production environment

### ISSUE THREAD

**Issue by dashanji** [v6d-io/v6d#916]
Describe your problem
---------------------

The current scheduler plugin isn't enough to meet the needs of the actual production environment, we should improve the scheduler plugin to make it easy for end-users to use the vineyard's ability in the k8s environment.

### What is the problem:

1. In the actual production environment, users need to align an order for a workflow.
2. At present, the CRD `GlobalObject` and `LocalObject` are considered observed resources, and we should get the workload that produces it through `annotation` or `label` and add ownereference for them.
3. There isn't a demo for users.

### Todo List:
- [ ] ~~Add some annotations for users to setup the workflow order etc.~~
- [ ] ~~Add  ownereference for `GlobalObject` and `LocalObject`.~~
- [x] Containerize the current [demo](https://v6d.io/notes/ml.html) so that it can be deployed in the k8s cluster and used in the operator.
- [x] Add an e2e test for the operator.
- [ ] ~~Add user manual.~~

**Comment by dashanji** [comment]
@sighingnow Could you please take a look at this?

**Comment by sighingnow** [comment]
I suggest design a tool `kubectl vineyard` or `vineyardctl` to interact with k8s, and to help user annotate their jobs or annotate vineyard objects.

**Comment by dashanji** [comment]
Could you elaborate on it a bit here? If we only want to annotate an object or a job, the command `kubectl annotate` is enough.
